import mongoose from "mongoose";

export const DEFAULT_PLANS = [
  {
    name: "Lite",
    slug: "lite",
    description: "Essential WhatsApp CRM tools for solo founders and small teams getting started.",
    active: true,
    currency: "INR",
    billingIntervals: {
      monthly: {
        price: 1499,
        originalPrice: 1999,
        label: "Monthly",
        discountPct: 0,
      },
      halfYearly: {
        price: 8095,
        originalPrice: 8994,
        label: "6 Months",
        discountPct: 10,
      },
      yearly: {
        price: 14390,
        originalPrice: 17988,
        label: "Yearly",
        discountPct: 20,
      },
    },
    features: [
      "campaigns",
      "forms",
      "leads",
      "pipeline",
      "quick_replies",
      "templates",
      "contacts",
    ],
    featureLabels: [
      { id: "campaigns", label: "Standard Broadcasts", included: true },
      { id: "leads", label: "Lead Management & Pipelines", included: true },
      { id: "forms", label: "Lead Generation Forms", included: true },
      { id: "templates", label: "WhatsApp Template Sync", included: true },
      { id: "quick_replies", label: "Quick Reply Shortcuts", included: true },
      { id: "ai_agent", label: "AI Bot & Autonomous Agents", included: false, hint: "Requires Professional" },
      { id: "automations", label: "Workflow Automations & Flows", included: false, hint: "Requires Professional" },
      { id: "integrations", label: "CRM & Webhook Integrations", included: false, hint: "Requires Professional" },
      { id: "api", label: "REST API & Webhooks", included: false, hint: "Requires Premium" },
    ],
    limits: {
      maxUsers: 2,
      maxContacts: 2500,
      maxCampaignsPerMonth: 20,
      maxMessagesPerMonth: 10000,
      maxAutomations: 0,
      maxAiAgents: 0,
      maxChannels: 1,
    },
    recommended: false,
    displayOrder: 1,
  },
  {
    name: "Professional",
    slug: "professional",
    description: "Complete WhatsApp growth suite with AI agents, automated flows, and team collaboration.",
    active: true,
    currency: "INR",
    billingIntervals: {
      monthly: {
        price: 3999,
        originalPrice: 4999,
        label: "Monthly",
        discountPct: 0,
      },
      halfYearly: {
        price: 21595,
        originalPrice: 23994,
        label: "6 Months",
        discountPct: 10,
      },
      yearly: {
        price: 38390,
        originalPrice: 47988,
        label: "Yearly",
        discountPct: 20,
      },
    },
    features: [
      "campaigns",
      "advanced_campaigns",
      "ai_agent",
      "automations",
      "advanced_analytics",
      "integrations",
      "drip_campaigns",
      "forms",
      "flows",
      "leads",
      "pipeline",
      "quick_replies",
      "templates",
      "contacts",
      "assignments",
    ],
    featureLabels: [
      { id: "campaigns", label: "Advanced Campaigns & Drips", included: true },
      { id: "ai_agent", label: "AI Chatbots & Auto-routing", included: true },
      { id: "automations", label: "Multi-Step Visual Flow Automations", included: true },
      { id: "leads", label: "Full Pipeline & Deal Stages", included: true },
      { id: "advanced_analytics", label: "Performance & Delivery Analytics", included: true },
      { id: "integrations", label: "Third-party Webhooks & Integrations", included: true },
      { id: "forms", label: "Lead Capture Forms & Embedded URLs", included: true },
      { id: "assignments", label: "Smart Round-Robin Agent Routing", included: true },
      { id: "api", label: "Dedicated REST API & Raw Webhooks", included: false, hint: "Requires Premium" },
    ],
    limits: {
      maxUsers: 5,
      maxContacts: 15000,
      maxCampaignsPerMonth: 100,
      maxMessagesPerMonth: 50000,
      maxAutomations: 25,
      maxAiAgents: 2,
      maxChannels: 2,
    },
    recommended: true,
    displayOrder: 2,
  },
  {
    name: "Premium",
    slug: "premium",
    description: "High-throughput enterprise WhatsApp engine with full API access, high limits, and voice integrations.",
    active: true,
    currency: "INR",
    billingIntervals: {
      monthly: {
        price: 7999,
        originalPrice: 9999,
        label: "Monthly",
        discountPct: 0,
      },
      halfYearly: {
        price: 43195,
        originalPrice: 47994,
        label: "6 Months",
        discountPct: 10,
      },
      yearly: {
        price: 76790,
        originalPrice: 95988,
        label: "Yearly",
        discountPct: 20,
      },
    },
    features: [
      "campaigns",
      "advanced_campaigns",
      "ai_agent",
      "automations",
      "advanced_analytics",
      "integrations",
      "voice",
      "drip_campaigns",
      "forms",
      "flows",
      "leads",
      "pipeline",
      "api",
      "webhooks",
      "quick_replies",
      "templates",
      "contacts",
      "assignments",
    ],
    featureLabels: [
      { id: "campaigns", label: "Enterprise Campaigns & High Throughput", included: true },
      { id: "ai_agent", label: "Multi-Agent AI Ecosystem", included: true },
      { id: "automations", label: "Unlimited Flows & Trigger Logic", included: true },
      { id: "api", label: "Direct REST API & Outbound Webhooks", included: true },
      { id: "voice", label: "Voice & Call Integrations", included: true },
      { id: "integrations", label: "Custom ERP & CRM Integrations", included: true },
      { id: "assignments", label: "Advanced Queue & Skills Routing", included: true },
      { id: "advanced_analytics", label: "Custom BI Export & Audit Trails", included: true },
    ],
    limits: {
      maxUsers: 15,
      maxContacts: 100000,
      maxCampaignsPerMonth: 500,
      maxMessagesPerMonth: 250000,
      maxAutomations: 100,
      maxAiAgents: 10,
      maxChannels: 5,
    },
    recommended: false,
    displayOrder: 3,
  },
];

const subscriptionPlanSchema = new mongoose.Schema(
  {
    name: {
      type: String,
      required: true,
      trim: true,
    },
    slug: {
      type: String,
      required: true,
      unique: true,
      trim: true,
      index: true,
    },
    description: {
      type: String,
      default: "",
    },
    active: {
      type: Boolean,
      default: true,
      index: true,
    },
    currency: {
      type: String,
      default: "INR",
    },
    billingIntervals: {
      type: mongoose.Schema.Types.Mixed,
      required: true,
    },
    features: {
      type: [String],
      default: [],
    },
    featureLabels: {
      type: [
        {
          id: String,
          label: String,
          included: Boolean,
          hint: String,
        },
      ],
      default: [],
    },
    limits: {
      type: mongoose.Schema.Types.Mixed,
      default: () => ({}),
    },
    recommended: {
      type: Boolean,
      default: false,
    },
    displayOrder: {
      type: Number,
      default: 0,
    },
  },
  { timestamps: true },
);

export const SubscriptionPlan = mongoose.model(
  "SubscriptionPlan",
  subscriptionPlanSchema,
);
